### PR TITLE
fix(validation): issue #117: validator now accepts custom joi

### LINKED ISSUE #117: Custom `joi` in Validator options causes error
```typescript
class Foo {
    @jf.string()
    bar: string;
}

const customJoi = Joi;
const validator = new Validator({
    joi: customJoi,
});

const instance = new Foo();
expect(instance).toBeValid({ validator });
```

Fails with error:
```
Error: "joi" is not allowed
    at Object.<anonymous>.internals.Object.checkOptions (*snip*\joiful\node_modules\@hapi\joi\lib\types\any\index.js:105:19)
    at Object.<anonymous>.internals.Object._validateWithOptions (*snip*\joiful\node_modules\@hapi\joi\lib\types\any\index.js:758:18)
    at Object.<anonymous>.module.exports.internals.Any.root.validate (*snip*\joiful\node_modules\@hapi\joi\lib\index.js:145:23)
    at Validator.validateAsClass (*snip*\joiful\src\validation.ts:1892:38)
    at Validator.validate (*snip*\joiful\src\validation.ts:1832:19)
```

This is because the Joiful validator's options are passed to the Joi `validate()` method, which validates its options and rejects our additional args.

### PR DESCRIPTION
**Pull request by laurence-myers**
This fixes an issue where the Joiful Validator's options are passed to the Joi validate() method, which validates its options, and rejects our additional property of `joi`.

Also, add unit tests for `getJoi()`; because Validator no longer uses it, we lost some coverage.

Closes #117

### CODE REVIEW

File: src/validation.ts [hunk 1]
```diff
@@ -68,10 +68,24 @@ export class Validator {
     ) {
     }
 
+    /**
+     * Issue #117: Joi's `validate()` method dies when we pass it our own validation options, so we need to strip it
+     *  out.
+     * @url https://github.com/joiful-ts/joiful/issues/117
+     */
+    protected rectifyOptions(options: ValidationOptions | undefined): [typeof Joi, Joi.ValidationOptions?] {
```
Comment (codeandcats) [inline src/validation.ts]: nit: This is a little thing but unless there's a specific reason to return a tuple, I would by default return an object with properties. I find returning an object slightly more easier to understand because the properties have names to convey meaning. I do think tuples make sense in some situations, like for example in react hooks you often want to rename the elements returned by `useState`, so returning a tuple keeps it terse. But I don't think it offers much benefit here imho.

Comment (codeandcats) [inline src/validation.ts]: nit: Could we maybe name this `extractOptions` or `extractJoiOptions`? Not just because `rectify` makes me think of a `rectum`, okay mostly that. 🍑

File: test/unit/core.test.ts [hunk 2]
```diff
@@ -26,6 +27,30 @@ describe('checkJoiIsCompatible', () => {
...
+    });
+
+    it('should return the given Joi instance', () => {
+        const customJoi = Joi.extend({
+            base: Joi.string(),
+            name: 'string',
+        });
+        const result = getJoi({ joi: customJoi });
+        expect(result).toBe(customJoi);
+        expect(result).not.toBe(Joi);
```
Comment (codeandcats) [inline test/unit/core.test.ts:50]: 💯

File: test/unit/validation.test.ts [hunk 3]
```diff
@@ -103,6 +104,15 @@ describe('Validation', () => {
...
                 expect(result.error).toBeTruthy();
             });
+
+            it('should support a custom instance of Joi', () => {
+                validator = new Validator({
+                    joi: Joi,
+                });
+                const result = validator.validate(login);
+                expect(result.value).toEqual(login);
+                expect(result.error).toBe(null);
```
Comment (codeandcats) [inline test/unit/validation.test.ts]: With all these `'should support a custom instance of Joi'` tests, I don't believe we're actually testing which instance of joi it's using. Could we instead pass in a mocked version of joi that has a mocked validate method and check that it was called?

Something like...

```typescript
const joi = {
  validate: jest.fn()
} as Partial<typeof Joi> as typeof Joi;
validator = new Validator({ joi });
validator.validate(login);
expect(joi.validate).toHaveBeenCalled();
```

You might need to mock a return value for `validate` as well, and might be good to test what `joi.validate` is called with, but not essential imo.

**Review by codeandcats — COMMENTED** [review]
Awesome job catching that bug and raising a PR so quickly!! 👌🥇

Looks great, I just had a few small suggestions.

File: src/validation.ts (hunk 1 above)
Comment (laurence-myers) [reply src/validation.ts]: Fair enough. I thought arrays might be faster, as a micro-optimization, but a quick benchmark test shows they're slower than objects! That'll learn me. 😄

2020-03-21 13_11_57-Window

Comment (laurence-myers) [reply src/validation.ts]: 😆 Sure! (Originally I thought I'd also need to merge `defaultOptions`, but it wasn't necessary.)

File: test/unit/validation.test.ts (hunk 3 above)
Comment (laurence-myers) [reply test/unit/validation.test.ts]: Great point, I'll sort it!

**Comment by laurence-myers** [comment]
I think I've addressed everything. I took the opportunity to refactor some of the validation (Validator) tests.

**Review by codeandcats — APPROVED** [review]
Awesome job! 👍 🎉 

I noticed a few things that I thought could be simplified. Rather than commenting I just pushed some changes. Feel free to add any thoughts you have.

File: test/unit/validation.test.ts [hunk 4]
```diff
@@ -72,41 +73,34 @@ describe('ValidationResult', () => {
...
+            @string()
+            emailAddress?: string;
+
+            @string()
+            password?: string;
+        }
+        return Login;
     }
 
+    let Login: ReturnType<typeof getLoginClass>;
```
Comment (codeandcats) [inline test/unit/validation.test.ts:88]: This way `Login` is properly typed.

File: test/unit/validation.test.ts [hunk 5]
```diff
@@ -120,24 +114,20 @@ describe('Validation', () => {
...
         login.emailAddress = 'joe@example.com';
-        Login = LoginClass;
-        mockJoi = createMockJoi();
-    });
-
-    afterEach(() => {
-        mockJoi.array.mockReset();
-        mockJoi.object.mockReset();
-        mockJoi.validate.mockReset();
+        joi = partialOf<typeof Joi>({
```
Comment (codeandcats) [inline test/unit/validation.test.ts:120]: I use `partialOf` in most of my TS tests. It's a just ridiculously simple but handy function for enforcing that your mock is mocking actual properties of your target type and that they are implemented correctly, and then pretends to return the entire target type. Useful just for testing purposes.

Comment (laurence-myers) [reply test/unit/validation.test.ts:120]: That looks handy. Might need a bit more type finagling to support the mock function properties. 

In the changes I made, I wanted to see if we could make it type safe all the way through from tests to main implementation. This included some changes so that functions required only a subset of `Joi`'s methods, instead of a complete `Joi` insdtance. I think now, using `partialOf()`, if you were to remove the mocked `array` property, it wouldn't error at compile time, only runtime. (Not a big problem since it's test code.)

If we don't want that level of type-safety between the tests and the main code, should we revert the changes I made to `validation.ts` and `getJoiSchema()`? I changed their signatures so that the `joi` arguments only needed the minimum required properties (`array`, `object`, `validate`).

Comment (codeandcats) [reply test/unit/validation.test.ts:120]: > If we don't want that level of type-safety between the tests and the main code, should we revert the changes I made to validation.ts and getJoiSchema()?

Up to you. 😃  I hear you regarding complete type-safety in tests. I don't have a strong opinion on it as I do this with my tests and have gotten used to it. As you say, if somethings not implemented you usually know about it pretty quick because your tests fail. But yeah if you prefer you can undo my commit and just take any bits you like.

Comment (laurence-myers) [reply test/unit/validation.test.ts:120]: Alright, I think let's keep the current changes as-is.

**Comment by Roms1383** [comment]
Hi guys I've just ran into that very issue,
do you plan to release this fix anytime soon by any chance ?

**Comment by codeandcats** [comment]
Hi @Roms1383, sorry for the delay. I've just published 2.0.1 now.
